### PR TITLE
test(vllm): remove unsupported prefill migration test

### PR DESCRIPTION
**Pull request by alec-flowers**
## Summary

- remove the permanently skipped vLLM prefill-migration test and its stale timing entry
- remove 8 matrix nodes that described a capability Dynamo does not implement
- keep the supported aggregated, KV-transfer, and decode migration tests unchanged

## Support evidence and decision

This is intentionally a removal rather than an unskip:

- Dynamo's `Migration` operator wraps the complete prefill-to-decode pipeline. On a migratable error, `RetryManager` clones and reissues the `PreprocessedRequest` through that pipeline.
- The migrator accumulates generated response token IDs. During prefill there are no generated response tokens to preserve, and the vLLM prefill path exposes no checkpoint/export/restore mechanism for partially computed prefill KV state.
- Consequently, a failure during prefill can at most restart and recompute the prompt on another prefill worker. That is request replay/new-request recovery, not migration of in-flight prefill state.
- The test was introduced in #5448 already marked `xfail` with `Prefill migration not yet supported`; it was later converted to an unconditional skip. It never represented a supported regression boundary.
- The test's assertion only checked eventual request success, so even an `xpass` could not distinguish full recomputation from state migration.

A permanently skipped hypothetical test has no regression sensitivity and should not remain in the nightly denominator. If partial prefill-state transfer is implemented later, it needs a new test with an observable state-reuse contract.

## Validation

- exact nightly image collection before: `28 tests collected`
- exact nightly image collection after: `20 tests collected` (8 unsupported prefill nodes removed)
- `python3 -m py_compile tests/fault_tolerance/migration/test_vllm.py`
- `git diff --check`
- scoped pre-commit formatting, lint, spelling, and hygiene hooks passed
- repository-wide `pytest-marker-report` reached the changed file and reported `tests/fault_tolerance/migration/test_vllm.py: 20`, then failed while collecting unrelated suites because the shared test port allocator was exhausted

No GPU run was needed: this change only deletes an unconditionally skipped test, and production-code inspection conclusively shows that its claimed state-transfer capability is absent.

## Merge dependency

**Resolved.** [#13716](https://github.com/ai-dynamo/dynamo/pull/13716) merged as `759cb4e3ea31cf6e20902a74da41cbaf8f86f2a1`. On August 24, 2026, the complete four-layer stack was rebased onto that `main` commit. This layer's rebased head is `8477ac88b2061f73be9075b43f218b8b3c1d2ab7`.

## Stack navigation

1. [#13684 — Aggregate migration](https://github.com/ai-dynamo/dynamo/pull/13684)
2. [#13692 — Prefill removal](https://github.com/ai-dynamo/dynamo/pull/13692) · [DYN-4118](https://linear.app/nvidia/issue/DYN-4118)
3. [#13693 — Decode migration](https://github.com/ai-dynamo/dynamo/pull/13693) · [DYN-4119](https://linear.app/nvidia/issue/DYN-4119)
4. [#13694 — KV-transfer migration](https://github.com/ai-dynamo/dynamo/pull/13694) · [DYN-4120](https://linear.app/nvidia/issue/DYN-4120)

This PR is layer **2** and targets `codex/vllm-agg-migration`. Review and merge the stack in order.

---

<a href="https://nvidia.devinenterprise.com/review/ai-dynamo/dynamo/pull/13692" target="_blank">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open in Devin Review
  </picture>
</a>

## Summary by CodeRabbit

* **Tests**
  * Removed an outdated prefill migration test and its associated execution-time entry.
  * Aggregated, key-value transfer, and decode migration coverage remains unchanged.

### CODE REVIEW

**Comment by alec-flowers** [comment]
## Pre-merge qualification completed

We exercised the full stacked migration module in the real **vllm-runtime / Test cuda13.0, amd64** GPU lane before returning the supported tests to nightly.

Qualification evidence from the [top-of-stack GPU job](https://github.com/ai-dynamo/dynamo/actions/runs/32686029622/job/97318954122):

- supported migration cases: **14/14 passed** (8 aggregate, 4 decode, 2 KV-transfer)
- target skips/xfails: **0**
- target retries/reruns: **0 observed**
- target durations: **78–102s**

This layer intentionally removes the unsupported prefill-migration test, so no prefill node should execute. The qualified stack therefore ends with 14 executable nightly cases and no permanently skipped prefill outcomes. The rebased final layer commit is `9cb673fcc7`.

**Comment by alec-flowers** [comment]
### Merge dependency: #13716

This stack must wait for [#13716](https://github.com/ai-dynamo/dynamo/pull/13716), which pins `plotext<6` for the aiconfigurator profiler/image path. Without that pin, the relevant image/profiler path can fail even though the migration cases themselves qualified successfully.

After #13716 merges, we will rebase the four PRs onto the updated `main` in stack order and verify the post-rebase required checks before merging.

**Comment by alec-flowers** [comment]
Dependency/rebase update:

- [#13716](https://github.com/ai-dynamo/dynamo/pull/13716) merged as `759cb4e3ea31cf6e20902a74da41cbaf8f86f2a1`.
- A fresh fetch showed `origin/main` at that exact commit, and Git ancestry verification passed.
- The four migration branches were rebased bottom-to-top and published with exact force-with-lease guards.
- This PR's rebased head is `8477ac88b2061f73be9075b43f218b8b3c1d2ab7`.
- Rebase validation passed: patch-equivalent `git range-diff`, clean stack ancestry/diffs, Python compilation, and a 14-case static marker gate (8 aggregate + 4 decode + 2 KV-transfer; all nightly; no skip/xfail/pre-merge; timeouts 290/350/350 seconds).

Post-rebase GitHub checks are being monitored separately.

**Comment by alec-flowers** [comment]
Stack transition / CI update:

- [#13684](https://github.com/ai-dynamo/dynamo/pull/13684) was squash-merged to `main` as `ae290631413b63a03317e9da71d48f1a1a3d0c5b`.
- GitHub automatically retargeted #13692 to `main` and restacked the three remaining branches. This PR is now `main` <- `bec7d576c245fa05c6ceceab5e92ded60ff4d446`.
- The automatic restack was audited: each remaining layer is still one commit, all old-to-new range-diffs are patch-equivalent, and the aggregate migration test files in the merge match the former base-layer head.
- Both evidence-backed retries of the earlier runner-pod infrastructure failures completed successfully.
- All latest current-head checks across #13692, #13693, and #13694 are terminal with no failures. The cancelled duplicate Pre Merge checks briefly shown on #13693 were superseded by a successful later run.
- Unresolved review threads across the four-PR sequence: 0.

**Review by jthomson04 — APPROVED** [review]
