### PR TITLE
fix: unbreak main — kv-router strict_priority call sites + vllm get_diff_sampling_param test mock

### PR DESCRIPTION
**Pull request by nnshah1**
Fixes a build break on `main`: `dynamo-kv-router` does not compile (`E0061`).

## Cause
A semantic merge conflict between two PRs that merged the same day and do not overlap textually:

- **#10638** (`feat(kv-router): add per-request strict priority tiers`, merged ~22:54 UTC) added a new `strict_priority: u32` parameter to `KvScheduler::schedule_with_block_hashes` and updated all call sites that existed at the time.
- **#10641** (`feat(kv-router): add runtime-free selection service`, merged earlier ~16:28 UTC) added new callers — `select` / `select_and_reserve` in `services/selection/core/mod.rs` — that #10638 never saw, so they were not updated.

Git merged both cleanly (different files), but the result calls the 17-arg method with 16 args:

```
error[E0061]: this method takes 17 arguments but 16 arguments were supplied
  --> lib/kv-router/src/services/selection/core/mod.rs:429:14
note: method defined here
  --> lib/kv-router/src/scheduling/local.rs:254:18
```

This fails the build job on every open PR.

## Fix
Pass `strict_priority = 0` (the baseline tier) at both call sites. `strict_priority` is the high-order component of the scheduling sort key `(strict_priority, policy_score)`; `0` is the default tier and preserves the pre-#10638 behavior of these callers (which had no concept of strict priority).

Verified locally with `cargo check -p dynamo-kv-router` (clean).

cc @PeaBrane (author of both #10638 and #10641) — flagging in case you would rather wire `strict_priority` through `SelectRequest` instead of defaulting; this PR is the minimal unbreak.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

---

<a href="https://nvidia.devinenterprise.com/review/ai-dynamo/dynamo/pull/10689" target="_blank">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open in Devin Review
  </picture>
</a>

## Summary by CodeRabbit

* **Refactor**
  * Adjusted internal priority handling during selection operations to improve request scheduling efficiency.

## Related Issues
Standalone build fix — does not close a tracked issue. Resolves the `dynamo-kv-router` `E0061` build break introduced on `main` by the #10638 + #10641 merge interaction.

---

## Update: second independent main break folded in (commit d41d1bd3bd)
While validating CI, a **second** broken-main failure surfaced — unrelated to kv-router and to this PR's original diff:

- **#10667** (`fix(vllm): reuse engine model config`) changed `llm_engine.start()` to read sampling params from `vllm_config.model_config.get_diff_sampling_param()`.
- **#10648** (`fix(vllm): normalize unified served model name`) added `test_unified_start_returns_normalized_served_model_name` with a mock that only puts `get_diff_sampling_param` on `create_model_config()` — not on `vllm_config.model_config` — so the test raises `AttributeError` on current `main`.

Same concurrent-merge pattern as the kv-router break. Because these are two **independent** breaks on `main`, no single-fix PR can reach green CI in isolation — so both unbreaks are bundled here so this PR can actually go green and unblock everyone. The vllm change is a 1-line test-mock fix (returns `{}`, matching the pre-#10667 path and the sibling test).

### CODE REVIEW

File: lib/kv-router/src/services/selection/core/mod.rs [hunk 1]
```diff
@@ -438,6 +438,7 @@ impl SelectionCore {
                 false,
                 req.prompt.lora_name.clone(),
                 req.priority_jump.unwrap_or_default(),
+                0, // strict_priority: baseline tier
```
[the remark this answers is not in the document]
Comment (nnshah1) [reply lib/kv-router/src/services/selection/core/mod.rs]: Correct, and intentional for this PR. This is a build-unbreak only: `strict_priority = 0` (baseline tier) restores the pre-#10638 behavior of these call sites. Wiring `strict_priority` through `SelectRequest` / `SelectAndReserveRequest` (as `push_router/selection.rs` and the C bindings already do) is a feature decision for the selection-service owner — flagged to @PeaBrane in the PR description as a possible follow-up. Keeping this PR minimal so it can land fast and unblock the build for all open PRs.

[the remark this answers is not in the document]
Comment (nnshah1) [reply lib/kv-router/src/services/selection/core/mod.rs]: Addressed in e8595b0789: added an optional `strict_priority: Option<u32>` field to both `SelectRequest` and `SelectAndReserveRequest` (mirroring `priority_jump`, `#[serde(default)]`) and changed the call sites to `req.strict_priority.unwrap_or(0)`. Selection-service callers can now set a strict priority tier; omitting it defaults to baseline tier 0, so it is fully backward compatible. The feature gap is closed.

**Review by PeaBrane — APPROVED** [review]

**Comment by nnshah1** [comment]
Heads-up @PeaBrane: folded a second, independent main-unbreak into this PR (commit `d41d1bd3bd`) — a 1-line vLLM test-mock fix for `get_diff_sampling_param` (broken by #10667 ↔ #10648, same concurrent-merge pattern as the kv-router issue). Bundled because `main` currently has two independent breaks and neither fix can reach green CI on its own. Flagging since it widens scope beyond the kv-router change you approved.
