### PR TITLE
refactor: standardize Prometheus metric naming conventions (part 1)

### PR DESCRIPTION
**Pull request by keivenchang**
#### Overview:

This PR improves consistency in Prometheus naming conventions and updating related documentation. No functionality has been changed.

#### Details:

• Updated metrics collection and prometheus naming in lib/runtime/src/metrics/prometheus_names.rs
• Updated service metrics handling in lib/runtime/src/service.rs and lib/llm/src/http/service/metrics.rs
• Updated metrics deployment documentation in deploy/metrics/README.md

#### Where should the reviewer start?

Focus on lib/runtime/src/metrics/prometheus_names.rs for the core naming convention changes, then review lib/runtime/src/service.rs for service-level metrics updates.

/coderabbit profile chill

### CODE REVIEW

**Comment by grahamking** [comment]
Code Rabbit making some interesting points.

File: deploy/metrics/README.md [hunk 1]
```diff
@@ -40,7 +40,7 @@ As of Q2 2025, Dynamo HTTP Frontend metrics are exposed when you build container
 
 The core Dynamo backend system automatically exposes metrics with the `dynamo_component_*` prefix for all components that use the `DistributedRuntime` framework:
 
-- `dynamo_component_inflight_requests`: Requests currently being processed (gauge)
+- `dynamo_component_inflight_requests_total`: Requests currently being processed (gauge)
```
[the remark this answers is not in the document]
Comment (keivenchang) [reply deploy/metrics/README.md]: In https://github.com/ai-dynamo/dynamo/pull/2914, Graham said: "This should end with _count or _total and so on, indicating the unit. Same for INFLIGHT_REQUESTS below."

File: lib/llm/src/http/service/metrics.rs [hunk 2]
```diff
@@ -96,7 +96,8 @@ impl Metrics {
     ///
     /// The following metrics will be created with the configured prefix:
     /// - `{prefix}_requests_total` - IntCounterVec for the total number of requests processed
-    /// - `{prefix}_inflight_requests` - IntGaugeVec for the number of inflight requests
+    /// - `{prefix}_inflight_requests_total` - IntGaugeVec for the number of inflight requests
+    /// - `{prefix}_client_disconnects_total` - IntGauge for the number of connections dropped by clients
     /// - `{prefix}_request_duration_seconds` - HistogramVec for the duration of requests
```
[the remark this answers is not in the document]
Comment (keivenchang) [reply lib/llm/src/http/service/metrics.rs]: Unfortunately, Rabbit is starting to become a bit pedantic and not helpful.

* Graham and I think that having unit in the name is very helpful, and `_total` is appropriate in inflight_requests_total.
* Changing from IntGauge => IntCounter is not my call. You should ask @michaelfeil whether this is appropriate. And if done, it should be in a separate PR related to client disconnects (e.g. I have no idea why/how it is used).

File: lib/runtime/examples/system_metrics/README.md [hunk 3]
```diff
@@ -62,7 +62,7 @@ The `dynamo_component_errors_total` metric includes the following error types:
 - `dynamo_component_request_duration_seconds` - Request processing time
 
 ### Gauges
-- `dynamo_component_inflight_requests` - Number of requests currently being processed
+- `dynamo_component_inflight_requests_total` - Number of requests currently being processed
```
[the remark this answers is not in the document]
Comment (keivenchang) [reply lib/runtime/examples/system_metrics/README.md]: Two human beings think that, for the sake of consistency, having a unit as the suffix (e.g. _total) will be consistent. See other examples in prometheus_names.rs.

File: lib/runtime/src/metrics/prometheus_names.rs [hunk 4]
```diff
@@ -46,7 +46,10 @@ pub mod frontend_service {
     pub const REQUESTS_TOTAL: &str = "requests_total";
 
     /// Number of inflight requests
-    pub const INFLIGHT_REQUESTS: &str = "inflight_requests";
+    pub const INFLIGHT_REQUESTS_TOTAL: &str = "inflight_requests_total";
+
+    /// Number of connections dropped by clients
+    pub const CLIENT_DISCONNECTS_TOTAL: &str = "client_disconnects_total";
```
[the remark this answers is not in the document]
Comment (keivenchang) [reply lib/runtime/src/metrics/prometheus_names.rs]: Rabbit is being very repetitive.

File: lib/runtime/src/pipeline/network/ingress/push_handler.rs [hunk 5]
```diff
@@ -73,7 +73,7 @@ impl WorkHandlerMetrics {
         )?;
 
         let inflight_requests = endpoint.create_intgauge(
-            work_handler::INFLIGHT_REQUESTS,
+            work_handler::INFLIGHT_REQUESTS_TOTAL,
             "Number of requests currently being processed by work handler",
             metrics_labels,
         )?;
```
[the remark this answers is not in the document]
Comment (keivenchang) [reply lib/runtime/src/pipeline/network/ingress/push_handler.rs:67]: Looks like Rabbit likes to repeat the same thing over and over again.

File: lib/llm/src/http/service/metrics.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (michaelfeil) [reply lib/llm/src/http/service/metrics.rs]: Fine with me. We have not rolled out the version yet (assuming you talk about the cancelled request counter, answering from mobile)

File: deploy/metrics/README.md (hunk 1 above)
[the remark this answers is not in the document]
Comment (keivenchang) [reply deploy/metrics/README.md]: Ok. Removed _total from gauge.

File: lib/runtime/examples/system_metrics/README.md (hunk 3 above)
[the remark this answers is not in the document]
Comment (keivenchang) [reply lib/runtime/examples/system_metrics/README.md]: I removed _total from gauge. Done.

File: lib/llm/src/http/service/metrics.rs [hunk 6]
```diff
@@ -117,7 +117,8 @@ impl Metrics {
     ///
     /// The following metrics will be created with the configured prefix:
     /// - `{prefix}_requests_total` - IntCounterVec for the total number of requests processed
-    /// - `{prefix}_inflight_requests` - IntGaugeVec for the number of inflight requests
+    /// - `{prefix}_inflight_requests` - IntGaugeVec for the number of inflight/concurrent requests
+    /// - `{prefix}_disconnected_clients` - IntGauge for the number of disconnected clients
```
Comment (keivenchang) [inline lib/llm/src/http/service/metrics.rs:138]: The person who added this forgot to update the comments.

File: lib/llm/src/http/service/metrics.rs [hunk 7]
```diff
@@ -148,16 +149,16 @@ impl Metrics {
...
                 "Number of inflight requests",
             ),
             &["model"],
         )
         .unwrap();
 
         let client_disconnect_gauge = prometheus::IntGauge::new(
-            frontend_metric_name("client_disconnects"),
-            "Number of connections dropped by clients",
+                frontend_metric_name(frontend_service::DISCONNECTED_CLIENTS),
```
Comment (keivenchang) [inline lib/llm/src/http/service/metrics.rs]: The person who added this didn't use the constant, so I'm adding it for him.

**Review by grahamking — APPROVED** [review]

**Review by biswapanda — APPROVED** [review]
lgtm

**Comment by keivenchang** [comment]
I made a bad merge and a bad upload. Please ignore until the next push.

File: lib/llm/tests/http_metrics.rs [hunk 8]
```diff
@@ -386,6 +386,28 @@ mod integration_tests {
...
+        // Manually update metrics for the registered model
+        // This simulates what the ModelWatcher would do in production
+        if let Some(etcd_client) = distributed_runtime.etcd_client() {
+            let model_entries = service.model_manager().get_model_entries();
+            for entry in model_entries {
+                if entry.name == local_model.service_name() {
+                    if let Err(e) = service
+                        .state()
+                        .metrics_clone()
+                        .update_metrics_from_model_entry_with_mdc(&entry, &etcd_client)
```
Comment (rmccorm4) [inline lib/llm/tests/http_metrics.rs]: Was there still more to the bad merge?

Seeing this failed check:
```
error[E0599]: no method named `update_metrics_from_model_entry_with_mdc` found for struct `Arc<dynamo_llm::http::service::Metrics>` in the current scope
   --> lib/llm/tests/http_metrics.rs:398:26
    |
395 |                       if let Err(e) = service
    |  _____________________________________-
396 | |                         .state()
397 | |                         .metrics_clone()
398 | |                         .update_metrics_from_model_entry_with_mdc(&entry, &etcd_client)
    | |_________________________-^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
help: there is a method `update_metrics_from_mdc` with a similar name, but with different arguments
   --> /workspace/lib/llm/src/http/service/metrics.rs:475:5
    |
475 |     pub fn update_metrics_from_mdc(&self, card: &ModelDeploymentCard) -> anyhow::Result<()> {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Comment (keivenchang) [reply lib/llm/tests/http_metrics.rs]: I completely missed this case. I ran tests but this was in the #ignore and didn't get run. How did you get the tests to run this one even with the #ignore flag?
