### PR TITLE
fix(vllm): MultiModalUUIDDict import compatibility and TokensPrompt import consistency

### PR DESCRIPTION
**Pull request by VincyZhang**
#### Overview:

Add vllm version compatibility for `MultiModalUUIDDict` import. The vllm 0.19.0 bump (#7894) moved this symbol to `vllm.inputs`, breaking XPU builds still pinned to vllm 0.16.0.

#### Details:

**components/src/dynamo/vllm/multimodal_utils/protocol.py**

`MultiModalUUIDDict` was introduced in vllm commit 749be00a9 and originally lived in `vllm.multimodal.inputs`. The vllm 0.19.0 bump PR (#7894) consolidated the import to `from vllm.inputs import MultiModalUUIDDict, TokensPrompt`, which works for CUDA builds (vllm>=0.19) but breaks XPU builds pinned to vllm 0.16.0 — that version does not export `MultiModalUUIDDict` from `vllm.inputs`.

This PR adds a try/except fallback: first try `vllm.inputs` (vllm>=0.19), then fall back to `vllm.multimodal.inputs` (vllm<0.19).

**Revert plan**: This workaround can be reverted once #7648 (XPU vllm version bump to 0.19+) merges and XPU CI no longer depends on vllm<0.19. See: https://github.com/ai-dynamo/dynamo/pull/7648

#### Where should the reviewer start?

- [components/src/dynamo/vllm/multimodal_utils/protocol.py](components/src/dynamo/vllm/multimodal_utils/protocol.py#L25-L31) for the import fallback logic

#### Related Issues:

- Fixes XPU CI import failure caused by #7894
- Relates to #7648 (revert this workaround after merge)

**Changes**

## Summary by CodeRabbit

* **Refactor**
  * Updated internal module import paths across multimodal components to improve code organization and consistency.

### CODE REVIEW

**Comment by VincyZhang** [comment]
@alec-flowers  Would you please take a look here? This import error occurs when vllm <0.19.0.
```ImportError: cannot import name 'MultiModalUUIDDict' from 'vllm.inputs'```

**Review by nv-anants — APPROVED** [review]

**Review by dmitry-tokarev-nv — APPROVED** [review]

**Comment by VincyZhang** [comment]
The `docs link check` failure seems due to network. Can we get this PR merged? @nv-anants  @dmitry-tokarev-nv
