### PR TITLE
feat(common): add managed artifact storage with fsspec (4/6)

### PR DESCRIPTION
**Pull request by biswapanda**
## Purpose

Add operator-managed artifact destinations through fsspec so clients can name an approved storage profile and object key without receiving or supplying provider credentials. The request shape is provider-neutral; the MVP runtime is deliberately restricted to S3-compatible fsspec backends.

## What changes

- Adds the `managed_fsspec` target with only `profile` and relative `object_key` in the request.
- Loads operator-owned profile configuration from `DYN_GENERATION_ARTIFACT_STORAGE_PROFILES`.
- Requires each profile to define a storage URL, storage options, one or more allowed key prefixes, and `create_only: true`.
- Keeps credentials and endpoint configuration in the worker environment rather than in the API request.
- Enables managed delivery only when `DYN_GENERATION_ARTIFACT_ENABLE_MANAGED_FSSPEC` is explicitly set.
- Validates normalized relative keys and enforces the configured prefix before any storage I/O.
- Restricts the current implementation to `s3://` and `s3a://` profiles, including S3-compatible endpoints such as MinIO.
- Uses async fsspec with `mode=create`, a single PUT, bounded retries/timeouts, isolated filesystem instances, and bounded session cleanup.
- Adds `s3fs` with compatible aiobotocore/fsspec dependencies to the vLLM runtime image and verifies that the S3 filesystem plugin loads.

## Configuration and limits

- `DYN_GENERATION_ARTIFACT_MAX_BYTES` controls the managed object limit and cannot exceed the supported 64 MiB single-PUT ceiling.
- `DYN_GENERATION_ARTIFACT_MANAGED_TIMEOUT_SECONDS` controls the managed operation timeout.
- `DYN_GENERATION_ARTIFACT_STORAGE_PROFILES` is size-bounded and rejects unknown profile fields.
- The emitted object ID is `profile:object_key`; provider credentials and raw endpoint configuration are not returned.

## Extensibility boundary

fsspec provides the filesystem abstraction and profile model needed for additional blob providers, but this PR intentionally allowlists only S3-compatible schemes because create-only and async-write semantics must be verified per provider. Adding GCS, Azure Blob, or another implementation should extend the profile validator and add provider-specific contract/E2E tests without changing the artifact payload or public receipt schema.

This remains in `dynamo.common`; no `components/src/dynamo/artifacts` component is introduced.

## Reviewer guide

- `components/src/dynamo/common/generation_artifact_storage.py`: profile parsing, validation, and managed writer.
- `components/src/dynamo/common/tests/test_generation_artifact_storage_minio.py`: managed and presigned MinIO E2E.
- `components/src/dynamo/vllm/tests/test_generation_artifact_s3fs_contract.py`: create-only S3 contract.
- `container/templates/vllm_runtime.Dockerfile`: dependency installation and import/plugin smoke test.

## Validation

- Managed and presigned storage unit suite: 48 passed.
- s3fs create-only contract: passed.
- Local MinIO managed-fsspec and presigned-PUT E2E: 2 passed.
- Runtime dependency contract test passed.

## PR stack

Review and merge bottom-up. Each PR is based on the preceding stack branch, so its diff contains only that layer. The original umbrella [#14385](https://github.com/ai-dynamo/dynamo/pull/14385) remains open and unchanged as a reference.

| Order | PR | Layer |
| --- | --- | --- |
| 1 | [#14977](https://github.com/ai-dynamo/dynamo/pull/14977) | Protocol and opaque receipt projection |
| 2 | [#14979](https://github.com/ai-dynamo/dynamo/pull/14979) | vLLM binary format |
| 3 | [#14980](https://github.com/ai-dynamo/dynamo/pull/14980) | Presigned HTTP PUT delivery |
| 4 | **[#14976](https://github.com/ai-dynamo/dynamo/pull/14976)** | Managed fsspec storage |
| 5 | [#14975](https://github.com/ai-dynamo/dynamo/pull/14975) | Bounded vLLM capture |
| 6 | [#14978](https://github.com/ai-dynamo/dynamo/pull/14978) | vLLM and frontend integration |

### CODE REVIEW

File: components/src/dynamo/common/tests/test_generation_artifact_storage_minio.py [hunk 1]
```diff
@@ -0,0 +1,140 @@
...
+    pytest.mark.gpu_0,
+    pytest.mark.post_merge,
+]
+
+
+@pytest.fixture
+def minio_client(monkeypatch):
+    endpoint = os.environ.get("DYN_ARTIFACT_MINIO_ENDPOINT")
+    if not endpoint:
+        pytest.skip("set DYN_ARTIFACT_MINIO_ENDPOINT to run MinIO artifact E2E")
```
Comment (dmitry-tokarev-nv) [inline components/src/dynamo/common/tests/test_generation_artifact_storage_minio.py:34]: **[P2] The only test that touches a real object store never runs.** `components/src/dynamo/common/tests/test_generation_artifact_storage_minio.py:34`. The file is marked `e2e` plus `post_merge`, which no lane selects, and `DYN_ARTIFACT_MINIO_ENDPOINT` is set nowhere in the repo. The CI pytest action already starts MinIO on `localhost:9000` with `minioadmin`/`minioadmin`. Please wire the marker and the endpoint so this lane runs.

<details>
<summary>Measured: marker selection per lane, and the sidecar that is already there</summary>

Collected on the PR head with the repo `pyproject.toml`, so the root `conftest.py` default markers apply.

| file | markers | `pre_merge and vllm and gpu_0 and not e2e` | `(pre_merge or post_merge) and vllm and gpu_0` | sequential lane `pre_merge and not parallel and not defaulted and not (vllm or sglang or trtllm) and (gpu_0)` |
|---|---|---|---|---|
| `test_generation_artifact_storage.py` | unit, gpu_0, pre_merge | 0 (48 deselected) | 0 (48 deselected) | **48 collected** |
| `test_generation_artifact_s3fs_contract.py` | unit, vllm, gpu_0, pre_merge | **1 collected** | **1 collected** | 0 (1 deselected) |
| `test_generation_artifact_storage_minio.py` | e2e, integration, gpu_0, post_merge | 0 (2 deselected) | 0 (2 deselected) | 0 (2 deselected) |
| `tests/dependencies/test_generation_artifact_dependencies.py` | unit, gpu_0, pre_merge | 0 | 0 | **1 collected** |

The post-merge runtime lane is `pre_merge`-only today, so `post_merge` plus no backend marker means no lane picks the file up. Even in a lane that did pick it up, the fixture calls `pytest.skip` because `DYN_ARTIFACT_MINIO_ENDPOINT` is unset:

```
$ grep -rn DYN_ARTIFACT_MINIO . --include=*.yml --include=*.yaml --include=*.sh --include=*.py --include=*.toml
components/src/dynamo/common/tests/test_generation_artifact_storage_minio.py:32,34,35,36
```

`.github/actions/pytest/action.yml:76-96` already runs `quay.io/minio/minio` on port 9000 with `MINIO_ACCESS_KEY: minioadmin` and `MINIO_SECRET_KEY: minioadmin`, which are the exact defaults this fixture falls back to.

I ran the two tests against a local MinIO to confirm they pass and are worth running. Managed write, create-only reject, and the bytes left intact all behaved correctly.
</details>

File: components/src/dynamo/common/tests/test_generation_artifact_storage.py [hunk 2]
```diff
@@ -23,6 +27,163 @@ def _allow_test_presigned_hosts(monkeypatch) -> None:
...
+            ),
+            timeout=0.25,
+        )
+
+    assert time.monotonic() - started < 0.25
+    session.close.assert_awaited_once_with()
+
+
+@pytest.mark.asyncio
+@pytest.mark.parametrize("object_key", ["", "/absolute", "../escape", "a/../b", "a\\b"])
```
Comment (dmitry-tokarev-nv) [inline components/src/dynamo/common/tests/test_generation_artifact_storage.py:175]: **[P2] The unsafe-key test does not pin the path guards.** `components/src/dynamo/common/tests/test_generation_artifact_storage.py:175`. `match="object_key"` is also satisfied by the later prefix error, so I deleted both normalization guards in `_validate_object_key` and all 5 cases still passed. Please add a case that sits inside the allowed prefix.

```suggestion
@pytest.mark.parametrize(
    "object_key",
    ["", "/absolute", "../escape", "a/../b", "a\\b", "request-1/../../etc/passwd"],
)
```

<details>
<summary>Mutation result, both directions, and the suggestion verified</summary>

Mutation: delete the `"\\" in key or key.startswith("/")` clause and the whole `{"", ".", ".."}` part check from `_validate_object_key`.

| tree | `-k rejects_unsafe_object_keys` |
|---|---|
| head | 5 passed |
| guards deleted | **5 passed** (no signal) |
| head + the suggestion | 6 passed |
| guards deleted + the suggestion | **1 failed, 5 passed** |

Why the existing cases survive the mutation: every one of them still raises, just from a different control. With the guards gone, `"../escape"` and `"a/../b"` are rejected by the prefix check with `managed target object_key is outside the profile prefix`, which contains the string `object_key`, so `match=` is satisfied.

What the mutated code then accepts, with the test profile `allowed_prefixes: ["artifacts"]`:

```
'artifacts/../../../etc/passwd' -> WROTE 'bucket/root/artifacts/../../../etc/passwd'
```

against head:

```
'artifacts/../../../etc/passwd' -> managed target object_key is not normalized
```

The head code is correct. Nothing escapes the configured root on any input I tried. The gap is only that the test would not catch a regression.
</details>

**Review by dmitry-tokarev-nv — APPROVED** [review]
## Review of 4/6, managed fsspec storage

Approving. I verified the behavior of this layer by running it, including against a real MinIO. The path handling is sound and I found no way to escape the configured root.

Three P2 items stay open and none of them blocks: the MinIO end-to-end test never runs in CI, the unsafe-key test does not pin the path guards, and `asyncio.timeout` needs Python 3.11 while the declared floor is 3.10. I replied on the existing thread for the third one with my measurement and my reading of its severity. I deliberately deferred the floating `s3fs` range to a note rather than a finding.

<details>

<summary>What backends are reachable, and what is actually covered</summary>

The profile validator allows only `s3://` and `s3a://`, so S3 and S3-compatible endpoints are the whole reachable surface. `url_to_fs` would accept any fsspec protocol, but the scheme check at `generation_artifact_storage.py:472` rejects everything else before any I/O.

| backend | reachable | covered by a test that runs in CI |
|---|---|---|
| `s3://` real endpoint (AWS) | yes | no |
| `s3://` S3-compatible (MinIO) | yes | no, see the inline finding |
| `s3a://` | yes | no |
| any other fsspec protocol | no, rejected by the scheme check | yes, indirectly, by the profile tests |

What does run in CI: 48 unit tests in the sequential lane, all of which replace `url_to_fs` with a fake, and 1 s3fs contract test in the vLLM lane that drives the real `s3fs.S3FileSystem` and asserts `mode="create"` becomes `IfNoneMatch="*"`. That contract test is the strongest coverage here, and it is real. No test that talks to an object store runs today.
</details>

<details>

<summary>Path handling, case by case, measured</summary>

Profile `s3://bucket/root`, `allowed_prefixes: ["artifacts"]`. Nothing escaped the root.

| key | result |
|---|---|
| `artifacts/ok.bin` | wrote `bucket/root/artifacts/ok.bin` |
| `/etc/passwd` | rejected, must be relative |
| `artifacts/../../etc/passwd` | rejected, not normalized |
| `..`, `../artifacts/x` | rejected, not normalized |
| `artifacts\x.bin`, `C:\win\x` | rejected, must be relative |
| empty string | rejected, must be relative |
| `s3://evil/x`, `https://evil.test/x`, `file:///etc/passwd` | rejected, not normalized |
| `s3:evil/x` | rejected, outside the profile prefix |
| `artifacts//x`, `artifacts/./x`, `artifacts/x/` | rejected, not normalized |
| `artifacts/\x00x` | rejected, invalid |
| 1100-byte key | rejected, invalid |
| `artifacts/..%2fx`, `artifacts/%2e%2e/x` | written as a literal key, which is correct for S3 |
| `artifacts-evil/x`, `artifactsevil` | rejected, outside the profile prefix |

The prefix check uses `key == prefix or key.startswith(prefix + "/")`, so a sibling prefix cannot match.
</details>

<details>

<summary>Failure, partial writes, and what the caller receives</summary>

Run against MinIO on `127.0.0.1`, with a bucket created out of band.

| case | result |
|---|---|
| happy path | wrote, receipt `object_id='p:artifacts/a.bin'` |
| same key again | `ArtifactStorageError: managed artifact write failed`, original bytes intact |
| wrong credentials | same message, `__cause__=None` |
| no credentials | same message, `__cause__=None` |
| endpoint unreachable | same message, `__cause__=None` |
| bucket missing | same message, `__cause__=None` |

The caller receives one `ArtifactStorageError` with a fixed string in every failure case. No caller-supplied value reaches the message.

Partial writes: a 20 MiB payload produced a MinIO ETag with no part-count suffix, so it was a single PUT, not a multipart upload. Because `max_bytes` is capped at 64 MiB and `chunksize` is 64 MiB, every managed write is one conditional PUT. A half-written object cannot become visible.

Size bounds, measured: `MAX_BYTES` unset and a 64 MiB + 1 payload is rejected; `0`, `-5` and `999999999999` are rejected as outside the supported range; `abc` is rejected as invalid; `1024` with a 2048-byte payload is rejected. Reads are not part of this layer.
</details>

<details>

<summary>Secrets in errors and logs</summary>

I put `AKIAEXPOSEDKEY` and `SUPERSECRETVALUE` in `storage_options` and forced a failure, then rendered the full traceback the way a log handler would.

```
contains SUPERSECRETVALUE: False
contains AKIAEXPOSEDKEY:   False
contains 19100 (the endpoint port): False
contains minioadmin: False
```

`raise ... from None` suppresses the botocore context, so the endpoint URL does not reach a traceback either. The `ManagedFsspecTarget` repr carries only the profile name and the object key.
</details>

<details>

<summary>Mutation results, with the control that moved each one</summary>

Baseline on the head tree in a clean venv: 47 passed. Two presigned tests from the earlier stack layer fail locally because my sandbox blocks a loopback socket bind, and they fail the same way on every tree below.

| mutation | result | control |
|---|---|---|
| `mode="create"` becomes `"overwrite"` | 3 failed | the fake raises `FileExistsError`, and the s3fs contract test loses `IfNoneMatch="*"` |
| drop the prefix enforcement | 3 failed | `test_managed_target_is_operator_gated_and_prefix_scoped` |
| drop the `ENABLE_MANAGED_FSSPEC` gate | 3 failed | the same test |
| `chunksize` becomes 5 MiB | 3 failed | `test_managed_max_bytes_cannot_enable_multipart_upload` |
| drop the `max_bytes` ceiling | 3 failed | `test_managed_profile_and_limit_failures_are_explicit` |
| drop both path normalization guards | **no change** | none, see the inline finding |

Restoring the file returned the suite to the baseline.
</details>

<details>

<summary>Stack position and the new dependency</summary>

This is 4 of 6 and it cannot merge on its own. Its base is the branch of 3/6, which sits on 2/6, which sits on 1/6. All six are open and none has landed, so 1/6, 2/6 and 3/6 must go in first. `ManagedFsspecTarget` and the `managed_fsspec` settings shape are consumed by 6/6, so that contract is unproven inside this pull request. I read that as expected for a stack, not as a defect.

`s3fs>=2026.4.0,<2027.0` in `pyproject.toml` and `container/deps/requirements.vllm.txt` is a floating range, not a pin. The repo prefers explicit pins. I am not raising it as a finding, because the same file already floats `pillow` and `PyNvVideoCodec`, and because the s3fs contract test runs in the vLLM pre-merge lane and would catch a change to the `mode="create"` behavior the code depends on. Worth a sentence in the description saying the range is deliberate.
</details>

<details>

<summary>Where verification stopped</summary>

I did not test against AWS S3 itself, only against MinIO, so the AWS path is unverified. I did not run the vLLM runtime image build, so the Dockerfile import check is unverified by execution. The red checks on this pull request are yours to handle and I am not reporting them; I read them only to see whether they touched my findings, and they did not.
</details>

File: components/src/dynamo/common/generation_artifact_storage.py [hunk 3]
```diff
@@ -342,11 +436,106 @@ async def _put_presigned(data: bytes, target: PresignedHttpPutTarget) -> None:
...
+        )
+        if not filesystem.async_impl:
+            raise ArtifactStorageError(
+                "managed artifact profile must use an async fsspec backend"
+            )
+        path = "/".join(part for part in (root.rstrip("/"), target.object_key) if part)
+        session = None
+        operation_error = None
+        try:
+            async with asyncio.timeout(timeout):
```
[the remark this answers is not in the document]
Comment (dmitry-tokarev-nv) [reply components/src/dynamo/common/generation_artifact_storage.py:503]: Confirmed by running it, and the failure is quieter than it looks. On Python 3.10 every managed write fails, and the real cause is suppressed.

I read this as P2, not a blocker, because I found no Python 3.10 environment that this repo ships or tests. Container templates resolve to `python3.12`, and no CI job sets up 3.10. The defect is that the declared floor is `requires-python = ">=3.10"`, and `pyproject.toml:26` already avoids `typing.Self` for exactly that reason. Either the code must work on 3.10, or the floor must move.

<details>

<summary>Measured on 3.10.16 and 3.12.9, with the control</summary>

```
python 3.10.16
hasattr(asyncio,"timeout") = False
module imports on 3.10: OK
managed write on 3.10 -> ArtifactStorageError: managed artifact write failed
   underlying __context__: AttributeError("module 'asyncio' has no attribute 'timeout'")
```

Control on 3.12.9, same code, same fake filesystem: the write succeeds and returns a receipt. Against a real MinIO on 3.12 it also succeeds and honors create-only.

The `raise ... from None` at `generation_artifact_storage.py:526` sets `__suppress_context__`, so a rendered traceback shows only `managed artifact write failed`. An operator on 3.10 gets no hint that the cause is a missing `asyncio.timeout`.
</details>
