### ISSUE TITLE
[BUG][CI]: live.rs kvbm-offload test module fails to compile (missing Arc/Mutex import)

### ISSUE THREAD

**Issue by nicole-lihui** [ai-dynamo/dynamo#12252]
## Summary

`cargo test -p dynamo-mocker --features kvbm-offload` (or `replay-bench,kvbm-offload`) fails to compile on current `main`. This is exercised by the pre-merge CI step **"Run KVBM offload Mooncake trace test"** in `.github/workflows/pre-merge.yml` (`rust-tests (.)` job), so it fails on any PR that touches Rust code and triggers that job — unrelated to the PR's actual diff.

Discovered while investigating an unrelated CI failure on #12064 (`fix(ext-proc): support IPv6 EPP endpoints`), which does not touch `lib/mocker` at all

## Root cause

`lib/mocker/src/scheduler/vllm/live.rs`, in the `#[cfg(test)] mod tests` block:

```rust
#[cfg(feature = "kvbm-offload")]
use super::*;
...
#[cfg(feature = "kvbm-offload")]
#[derive(Default)]
struct CapturingKvSink {
    events: Mutex<Vec<(StorageTier, KvCacheEvent)>>,   // Mutex not in scope
}
...
let sink = Arc::new(CapturingKvSink::default());        // Arc not in scope
```

`use super::*` only re-exports what the parent module (`live.rs`) itself imports, but `live.rs` never imports `std::sync::{Arc, Mutex}` (conditionally or otherwise) — so the glob import doesn't bring them in. This was introduced by #11917 ("feat(mocker): add live request engine").

## Error

```
error[E0425]: cannot find type `Mutex` in this scope
   --> lib/mocker/src/scheduler/vllm/live.rs:283:17
    |
283 |         events: Mutex<Vec<(StorageTier, KvCacheEvent)>>,
    |                 ^^^^^ not found in this scope

error[E0433]: cannot find type `Arc` in this scope
   --> lib/mocker/src/scheduler/vllm/live.rs:322:20
    |
322 |         let sink = Arc::new(CapturingKvSink::default());
    |                    ^^^ use of undeclared type `Arc`

error: could not compile `dynamo-mocker` (lib test) due to 2 previous errors
```

## Suggested fix

Add, near the existing conditional import at the top of the file (`#[cfg(all(test, feature = "kvbm-offload"))] use std::time::Duration;`):

```rust
#[cfg(all(test, feature = "kvbm-offload"))]
use std::sync::{Arc, Mutex};
```

## Repro

```bash
cargo test --locked -p dynamo-mocker --features replay-bench,kvbm-offload replay_forces_g1_to_g2 --no-run
```

## CI evidence

- Failing run: https://github.com/ai-dynamo/dynamo/actions/runs/29987248685/job/89141781132
- Failing step: "Run KVBM offload Mooncake trace test"

**Comment by sachalmalick** [comment]
Closing as already fixed by #12075, which restored the missing KVBM test imports. #12254 duplicates the same change and should be closed as superseded.
