### ISSUE TITLE
[BUG]: examples/vllm_v0: ImportError for WorkerMetricsPublisher in v0.3.0

### ISSUE THREAD

**Issue by athreesh** [ai-dynamo/dynamo#1479]
### Describe the Bug

When running the V0 vLLM example with Dynamo CLI v0.3.0, the worker module fails to load:
ImportError: cannot import name 'WorkerMetricsPublisher' from 'dynamo.llm'

This seems to happen because examples/vllm_v0/components/worker.py still seems to reference WorkerMetricsPublisher, which was removed from the public dynamo.llm API in v0.3.0 and moved into runtime

The V0 example should ideally run out-of-the-box on v0.3.0, or could also be documented as only compatible with v0.2.x. 

Likely an easy PR --> update examples/vllm_v0/components/worker.py to remove or replace the WorkerMetricsPublisher import (see examples/vllm_v1 for reference)

### Steps to Reproduce

To Reproduce
	1. Clone the main branch (v0.3.0+) and setup env.
	2. Attempt to serve: cd examples/vllm_v0 + dynamo serve graphs.agg:Frontend -f configs/agg.yaml
	3. Observe error: ImportError: cannot import name 'WorkerMetricsPublisher' from 'dynamo.llm'

### Expected Behavior

The V0 example should run out-of-the-box on v0.3.0, or clearly documented as only compatible with v0.2.X

### Actual Behavior

ImportError: Failed to import module "graphs.agg": cannot import name 'WorkerMetricsPublisher' from 'dynamo.llm' (/home/nvidia/dynamo/venv/lib/python3.10/site-packages/dynamo/llm/__init__.py)

### Environment

Environment:
	•	Dynamo version: v0.3.0
	•	Python: 3.10
	•	OS: Ubuntu 22.04 (Minikube VM)
	•	CLI install: pip install . in venv
	•	vLLM image: nvcr.io/<org>/dynamo:latest-vllm

**Comment by bigdata2** [comment]
I also got the same error while running disaggregated mode from the examples/llm directory.

**Comment by rmccorm4** [comment]
Hi @athreesh, can you try running the example from the v0.3.0 branch? If you look, that code on v0.3.0 release should have the correct `KvMetricsPublisher` (not `WorkerMetricsPublisher`: https://github.com/ai-dynamo/dynamo/blob/v0.3.0/examples/vllm_v0/components/worker.py#L37). 

It was renamed after v0.3.0, and would not be expected to work on v0.3.0. For highest stability, you should run examples from the same release branch as the version you've running. It's possible the examples will change on `main` in between releases.
