### ISSUE TITLE
[BUG]: GPT-OSS-120B fails with FlashInfer attention sink error in Dynamo v1.0.0 (worked in v0.9.0)

### ISSUE THREAD

**Issue by changhyeonnam** [ai-dynamo/dynamo#7514]
### Describe the Bug

In Dynamo v0.9.0 (vLLM 0.14.1), disaggregated prefill/decode inference with GPT-OSS-120B worked correctly on NVIDIA B200 (Blackwell/SM100) using the default attention backend.

After upgrading to Dynamo v1.0.0 (vLLM 0.16.0), worker pods crash at 

startup with:

```
  NotImplementedError: FlashInfer backend currently does not support 
  attention sinks, please use trtllm on blackwell or flash attention 
  on earlier GPUs.
```

### Steps to Reproduce

Prerequisites:
- Dynamo v1.0.0 Kubernetes operator installed
- NVIDIA B200 GPU nodes available

1. Save the following manifest as disagg-repro.yaml and apply it:

   kubectl apply -f disagg-repro.yaml
```yaml
apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: vllm-disagg-repro
spec:
  services:
    Frontend:
      componentType: frontend
      volumeMounts:
        - name: pvc-gpt-oss-120b
          mountPoint: /opt/models
      replicas: 1
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:1.0.0
    VllmDecodeWorker:
      envFromSecret: hf-token-secret
      componentType: worker
      volumeMounts:
        - name: pvc-gpt-oss-120b
          mountPoint: /opt/models
      replicas: 1
      resources:
        requests:
          gpu: "1"
        limits:
          gpu: "1"
      envs:
        - name: SERVED_MODEL_NAME
          value: "openai/gpt-oss-120b"
        - name: MODEL_PATH
          value: "/opt/models/hub/models--openai--gpt-oss-120b/snapshots/b5c939de8f754692c1647ca79fbf85e8c1e70f8a"
        - name: HF_HOME
          value: /opt/models
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:1.0.0
          workingDir: /workspace/examples/backends/vllm
          command:
          - python3
          - -m
          - dynamo.vllm
          args:
            - --model
            - $(MODEL_PATH)
            - --served-model-name
            - $(SERVED_MODEL_NAME)
            - --disaggregation-mode
            - decode
            - --kv-transfer-config
            - '{"kv_connector":"NixlConnector","kv_role":"kv_both"}'
            - --max-model-len
            - "32000"
            - --enforce-eager
    VllmPrefillWorker:
      envFromSecret: hf-token-secret
      componentType: worker
      volumeMounts:
        - name: pvc-gpt-oss-120b
          mountPoint: /opt/models
      replicas: 1
      resources:
        requests:
          gpu: "1"
        limits:
          gpu: "1"
      envs:
        - name: SERVED_MODEL_NAME
          value: "openai/gpt-oss-120b"
        - name: MODEL_PATH
          value: "/opt/models/hub/models--openai--gpt-oss-120b/snapshots/b5c939de8f754692c1647ca79fbf85e8c1e70f8a"
        - name: HF_HOME
          value: /opt/models
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:1.0.0
          workingDir: /workspace/examples/backends/vllm
          command:
          - python3
          - -m
          - dynamo.vllm
          args:
            - --model
            - $(MODEL_PATH)
            - --served-model-name
            - $(SERVED_MODEL_NAME)
            - --disaggregation-mode
            - prefill
            - --max-model-len
            - "32000"
            - --enforce-eager
            - --kv-transfer-config
            - '{"kv_connector":"NixlConnector","kv_role":"kv_both"}'
```

2. Wait for VllmDecodeWorker or VllmPrefillWorker pod to start.

3. Observe the crash in pod logs:
   kubectl logs -f vllm-decode-or-prefill-worker-pod-name

### Expected Behavior

Disaggregated inference should work out-of-the-box as it did in Dynamo v0.9.0 (vLLM 0.14.1), without requiring explicit attention backend configuration.                                                  

### Actual Behavior

Worker pods fail at startup with the following error:
```
(EngineCore_DP0 pid=851) INFO 03-19 01:50:34 [flashinfer.py:582] TRTLLM attention is disabled because KV transfer (P/D disaggregation) is enabled. TRTLLM attention requires strictly contiguous KV cache tensors which may not be guaranteed with KV transfer.
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006] EngineCore failed to start.
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006] Traceback (most recent call last):
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 996, in run_engine_core
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]     engine_core = EngineCoreProc(*args, engine_index=dp_rank, **kwargs)
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/tracing/otel.py", line 178, in sync_wrapper
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]     return func(*args, **kwargs)
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 740, in __init__
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]     super().__init__(
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 113, in __init__
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]     num_gpu_blocks, num_cpu_blocks, kv_cache_config = self._initialize_kv_caches(
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/tracing/otel.py", line 178, in sync_wrapper
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]     return func(*args, **kwargs)
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 275, in _initialize_kv_caches
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]     self.model_executor.initialize_from_config(kv_cache_configs)
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/v1/executor/abstract.py", line 117, in initialize_from_config
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]     self.collective_rpc("initialize_from_config", args=(kv_cache_configs,))
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/v1/executor/uniproc_executor.py", line 75, in collective_rpc
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]     result = run_method(self.driver_worker, method, args, kwargs)
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/v1/serial_utils.py", line 459, in run_method
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]     return func(*args, **kwargs)
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/v1/worker/worker_base.py", line 316, in initialize_from_config
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]     self.worker.initialize_from_config(kv_cache_config)  # type: ignore
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/tracing/otel.py", line 178, in sync_wrapper
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]     return func(*args, **kwargs)
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 430, in initialize_from_config
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]     self.model_runner.initialize_kv_cache(kv_cache_config)
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 6066, in initialize_kv_cache
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]     self.initialize_metadata_builders(kv_cache_config, kernel_block_sizes)
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 5421, in initialize_metadata_builders
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]     attn_group.create_metadata_builders(
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/v1/worker/utils.py", line 48, in create_metadata_builders
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]     self.backend.get_builder_cls()(
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/v1/attention/backends/flashinfer.py", line 615, in __init__
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006]     raise NotImplementedError(
(EngineCore_DP0 pid=851) ERROR 03-19 01:50:34 [core.py:1006] NotImplementedError: FlashInfer backend currently does not support attention sinks, please use trtllm on blackwell or flash attention on earlier GPUs.
```

                                                                                                                                                                                                            
Workaround: Adding --attention-backend TRITON_ATTN to both prefill and decode worker args resolves the crash.


### Environment

- OS: Ubuntu 24.04.3 LTS (kernel 6.8.0-71-generic)                                                                                                                                                        
- Dynamo Runtime Version: v1.0.0 
- vLLM Version: 0.16.0 (was 0.14.1 in Dynamo v0.9.0)                                                                                                                                                      
- CPU Architecture: x86_64                                                                                                                                                                                
- GPU Architecture: NVIDIA B200                                                                                                                                                                           
- Kubernetes: v1.35.1 (kubespray, containerd 2.2.1)                                                                                                                                                       
- Python Version: 3.12.3                                                                                                                                                                                  

### Additional Context

**Root Cause Analysis:**                                                 

GPT-OSS-120B embeds attention sinks as a learned parameter (torch.nn.Parameter) in every attention layer, regardless of whether Sliding Window Attention (SWA) is active. vLLM detects this via `getattr(impl, "sinks", None) is not None` and sets has_sinks=True globally for the model.

On Blackwell (SM100), FlashInfer does not implement attention sinks — only TRTLLM does (flashinfer.py:615).

The failure chain in vLLM 0.16.0:
  1. P/D disaggregation (KV transfer) is enabled
  2. globally disabled TRTLLM when KV transfer is active
  3. FlashInfer is selected as fallback
  4. FlashInfer raises NotImplementedError — attention sinks not supported

In vLLM 0.14.1 (Dynamo v0.9.0), PR #33192 did not exist, so TRTLLM remained active with P/D disaggregation and attention sinks worked correctly.

**Upstream fix:**
vllm-project/vllm#34832 reverted the guard introduced by #33192,
re-enabling TRTLLM attention with KV transfer. This fix has been merged into vLLM main but is not yet included nvcr.io/nvidia/ai-dynamo/vllm-runtime:1.0.0 (vLLM 0.16.0).

**Suggested Fix:**
Upgrade the vLLM version bundled in vllm-runtime to include vllm-project/vllm#34832 (merged after v0.17.0 branch cut). 

**Workaround:**
Adding --attention-backend TRITON_ATTN to both prefill and decode worker args resolves the crash.

**Related upstream vllm PRs:**
- vllm-project/vllm#33192 (introduced the regression)
- vllm-project/vllm#34832 (upstream fix — revert of #33192)
- vllm-project/vllm#30919 (same NotImplementedError, non-disagg case)                                                                                                                         

### Screenshots

<img width="1439" height="647" alt="Image" src="https://github.com/user-attachments/assets/663d1644-7a5a-4d2e-8ade-c6967d20ff6d" />

**Comment by lakshyaj02** [comment]
I would like to work on this one!

**Comment by GuanLuo** [comment]
@changhyeonnam The recent Dynamo 1.1.0 ships with vLLM 0.19.0 which would contain the upstream fix you linked, could you try it out and see if the issue persists?

**Comment by changhyeonnam** [comment]
@GuanLuo Hi, thanks for the update! Tested with nvcr.io/nvidia/ai-dynamo/vllm-runtime:1.1.0 on B200 — the same issue no longer occurs, and workers start cleanly without the --attention-backend TRITON_ATTN workaround. GPT-OSS-120B disagg P/D runs as expected.
