### ISSUE TITLE
[BUG]: DeepSeek doesn't work with A100/L20 GPUs due to xFormers got an unexpected keyword argument 'q_lora_rank'

### ISSUE THREAD

**Issue by ky362** [ai-dynamo/dynamo#1901]
### Describe the Bug

DeepSeek MLA doesn't work with vLLM backend inside the v0.2.0/v0.3.1 container. Failed due to the xFormers doesn't recognize` q_lora_rank`.

<img width="1122" height="215" alt="Image" src="https://github.com/user-attachments/assets/b50e66d5-6398-41fd-adc7-90c780050d1e" />

Tried the following alternative attn backends but so far no solution yet:
xFormers - Rebuilding a newer xFormers inside container, but the vLLM in the container hard pins `xformers==0.0.29.post2`.  Tried to upgrade vLLM to v0.9x, too. The worker creation process gets stuck before the error shows up.
 
Flash-Attention-2 (v2.7.4) – rebuilt with SM 80 kernels, FA-2 imports fine, but vLLM logs
`Cannot use FlashAttention-2 backend for head size 576`

FlashInfer 0.2.7 – compiled SM 80 wheel, but vLLM still finds only the stub (~5 MB) that ships in the image; _flashinfer_impl.so never makes it onto the worker’s import path. The same q_lora_rank error shows up.

Any advice on how to run DS on A/L-series GPUs would be greatly helpful. Thank you!

### Steps to Reproduce

1. start nats/etcd/dynamo containers as usual
`docker compose -f deploy/docker-compose.yml up -d
./container/run.sh -it --name nodeB --mount-workspace -v /data01/:/data --image dynamo:v0.3.1-vllm`
2. Inside container:

`cd examples/llm/
dynamo serve graphs.agg_router:Frontend -f ./configs/test.yaml`

Model: RedHatAI/DeepSeek-V2.5-1210-FP8 (stored as a local copy at /data/deepseek-v2; the error can be reproduced using DeepSeek-R1, too)

The config file `test.yaml` looks like following:
`Common:
  model: /data/deepseek-v2
  block-size: 64
  max-model-len: 16384
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  enable-expert-parallel: true
  tensor-parallel-size: 8

Frontend:
  served_model_name: deepseek-ai/DeepSeek-V2
  endpoint: dynamo.Processor.chat/completions
  port: 8000

Processor:
  trust-remote-code: true
  router: round-robin
  common-configs: [model, block-size]

VllmWorker:
  trust-remote-code: true
  remote-prefill: true
  swap-space: 64 # GB per GPU
  conditional-disagg: false
  max-num-seqs: 256
  ServiceArgs:
    workers: 1
    resources:
      gpu: 8
  common-configs: [model, block-size, max-model-len, kv-transfer-config, enable-expert-parallel, tensor-parallel-size]

PrefillWorker:
  trust-remote-code: true
  max-num-batched-tokens: 16384
  ServiceArgs:
    workers: 1
    resources:
      gpu: 8
  common-configs: [model, block-size, max-model-len, kv-transfer-config, enable-expert-parallel, tensor-parallel-size]`

### Expected Behavior

The worker loads in the model and successfully spins up.

### Actual Behavior

Because FlashMLA only works for Hopper, the attn backend falls to xFormers.

<img width="935" height="342" alt="Image" src="https://github.com/user-attachments/assets/ad88b0be-d470-4f4c-ac9b-ad744f9e35bd" />

The worker failed as the xFormers in the container (`xformers==0.0.29.post2`) doesn't support `q_lora_rank`

<img width="1122" height="215" alt="Image" src="https://github.com/user-attachments/assets/f6a96b91-fb9d-40b1-b58f-4f6a0dff7dc9" />

### Environment

Server: Intel Xeon Platinum 8336C CPU + 8x A100-SXM4-80GB
Image: v0.3.1-vllm
Model: RedHatAI/DeepSeek-V2.5-1210-FP8 (stored as a local copy at /data/deepseek-v2; the error can be reproduced using DeepSeek-R1, too)
System Information:
OS: Ubuntu 24.04
Glibc Version: 2.39
GCC Version: 13.3.0
Cmake Version: 3.28.3
Rust Version: 1.87.0
Docker Version: N/A

Python Version: 3.12.3
Python Platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.39

Python Packages:
ai-dynamo: 0.3.1
ai-dynamo-runtime: 0.3.1
ai-dynamo-vllm: 0.8.4.post3
genai-perf: 0.0.13
nixl: 0.3.1
numpy: 2.2.6
nvidia-cublas-cu12: 12.4.5.8
nvidia-cuda-cupti-cu12: 12.4.127
nvidia-cuda-nvrtc-cu12: 12.4.127
nvidia-cuda-runtime-cu12: 12.4.127
nvidia-cudnn-cu12: 9.1.0.70
nvidia-cufft-cu12: 11.2.1.3
nvidia-curand-cu12: 10.3.5.147
nvidia-cusolver-cu12: 11.6.1.9
nvidia-cusparse-cu12: 12.3.1.170
nvidia-ml-py: Not installed
nvidia-nccl-cu12: 2.21.5
nvidia-nvjitlink-cu12: 12.4.127
nvidia-nvtx-cu12: 12.4.127
pyzmq: 27.0.0
tensorrt_llm: Not installed
torch: 2.6.0
torchaudio: 2.6.0
transformers: 4.53.0
tritonclient: 2.59.0
