### PR TITLE
fix(mocker): import Arc/Mutex for kvbm-offload live scheduler tests

### LINKED ISSUE #12252: [BUG][CI]: live.rs kvbm-offload test module fails to compile (missing Arc/Mutex import)
## Summary

`cargo test -p dynamo-mocker --features kvbm-offload` (or `replay-bench,kvbm-offload`) fails to compile on current `main`. This is exercised by the pre-merge CI step **"Run KVBM offload Mooncake trace test"** in `.github/workflows/pre-merge.yml` (`rust-tests (.)` job), so it fails on any PR that touches Rust code and triggers that job — unrelated to the PR's actual diff.

Discovered while investigating an unrelated CI failure on #12064 (`fix(ext-proc): support IPv6 EPP endpoints`), which does not touch `lib/mocker` at all

## Root cause

`lib/mocker/src/scheduler/vllm/live.rs`, in the `#[cfg(test)] mod tests` block:

```rust
#[cfg(feature = "kvbm-offload")]
use super::*;
...
#[cfg(feature = "kvbm-offload")]
#[derive(Default)]
struct CapturingKvSink {
    events: Mutex<Vec<(StorageTier, KvCacheEvent)>>,   // Mutex not in scope
}
...
let sink = Arc::new(CapturingKvSink::default());        // Arc not in scope
```

`use super::*` only re-exports what the parent module (`live.rs`) itself imports, but `live.rs` never imports `std::sync::{Arc, Mutex}` (conditionally or otherwise) — so the glob import doesn't bring them in. This was introduced by #11917 ("feat(mocker): add live request engine").

## Error

```
error[E0425]: cannot find type `Mutex` in this scope
   --> lib/mocker/src/scheduler/vllm/live.rs:283:17
    |
283 |         events: Mutex<Vec<(StorageTier, KvCacheEvent)>>,
    |                 ^^^^^ not found in this scope

error[E0433]: cannot find type `Arc` in this scope
   --> lib/mocker/src/scheduler/vllm/live.rs:322:20
    |
322 |         let sink = Arc::new(CapturingKvSink::default());
    |                    ^^^ use of undeclared type `Arc`

error: could not compile `dynamo-mocker` (lib test) due to 2 previous errors
```

## Suggested fix

Add, near the existing conditional import at the top of the file (`#[cfg(all(test, feature = "kvbm-offload"))] use std::time::Duration;`):

```rust
#[cfg(all(test, feature = "kvbm-offload"))]
use std::sync::{Arc, Mutex};
```

## Repro

```bash
cargo test --locked -p dynamo-mocker --features replay-bench,kvbm-offload replay_forces_g1_to_g2 --no-run
```

## CI evidence

- Failing run: https://github.com/ai-dynamo/dynamo/actions/runs/29987248685/job/89141781132
- Failing step: "Run KVBM offload Mooncake trace test"

### PR DESCRIPTION
**Pull request by nicole-lihui**
## Overview:

Fix a pre-existing compile failure in `dynamo-mocker`'s `kvbm-offload` feature that breaks the pre-merge "Run KVBM offload Mooncake trace test" CI step for any PR touching Rust code, regardless of what that PR actually changes.

## Details:

`lib/mocker/src/scheduler/vllm/live.rs`'s `#[cfg(feature = "kvbm-offload")] mod tests` block does `use super::*;` expecting to inherit `Arc`/`Mutex` from the parent module, but `live.rs` never imports those types itself (conditionally or otherwise), so the glob import brings in nothing. Building with `--features kvbm-offload` then fails with `E0425`/`E0433` ("cannot find type `Mutex`/`Arc` in this scope").

This was introduced by #11917 ("feat(mocker): add live request engine") and is only exercised by the CI step that explicitly enables `kvbm-offload`, so it silently breaks `rust-tests (.)` on every Rust PR without being caused by that PR's own diff. Discovered while investigating an unrelated CI failure on #12064.

Fix: add `use std::sync::{Arc, Mutex};` gated the same way the existing `Duration` import is (`#[cfg(all(test, feature = "kvbm-offload"))]`).

## Where should the reviewer start?

- `lib/mocker/src/scheduler/vllm/live.rs` (top-of-file imports, lines 6-9)

## Related Issues

**🔗 This PR is linked to an issue:**

- Closes #12252

### CODE REVIEW

**Comment by sachalmalick** [comment]
Thanks @nicole-lihui. The same import fix had already landed in #12075 before this PR was opened, and the tracking issue #12252 is now closed as resolved. Could you close this PR as superseded?
